### ISSUE TITLE
"A privacy reminder from Google"

### ISSUE THREAD

**Issue by passy** [itszero/kgcat#1]
Annoyingly, in my country Google displays you an update to their privacy policy in a lightbox you have to accept before performing any searches. `kgcat` picks this up and doesn't show anything else. :(
![screenshot 2016-02-21 11 26 22](https://cloud.githubusercontent.com/assets/9906/13202310/10bfb0c2-d88e-11e5-9acb-4c9ee0e9691a.png)

**Comment by itszero** [comment]
Thanks for reporting. I'll take a look at it. May I also ask which country are you in? It will help me reproduce the issue and solve it. :)

**Comment by sotojuan** [comment]
Is it possible for phantom or something else in the program to "fake" a location that doesn't require this? Awesome little tool, by the way!

**Comment by passy** [comment]
Sorry, of course. United Kingdom.

**Comment by itszero** [comment]
The fix has been released as 1.1.0.

**Comment by itszero** [comment]
@sotojuan Thanks! I don't think faking location helps tho, those privacy reminders are most likely IP-based.

**Comment by sotojuan** [comment]
Got it, just throwing out ideas. Glad it's fixed!

**Comment by passy** [comment]
Awesome, thank you! :raised_hands:
